# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# $cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle\

right_format = """$c$cmake\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$lua\
"""

format = """$username$hostname$localip\
$singularity$kubernetes\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$docker_context\
$package\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[directory]
truncation_length = 5
truncate_to_repo = false
style = "blue"
read_only = ""
repo_root_style = "bold cyan"
home_symbol = "󰋜"
[directory.substitutions]
"Downloads" = "󰉍"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = ""
style = "#aaaaaa"

[git_commit]
tag_symbol = "󰓹"

[git_status]
format = """\
([$staged$renamed$typechanged$count$modified](green) )\
([$untracked$deleted](red) )\
([$ahead_behind](green) )\
"""
deleted = "-$count"
staged = "+$count"
renamed = "~$count"
modified = "!$count"
untracked = "?$count"
ahead = "⇡$count"
behind = "⇣$count"

[package]
disabled = true

[c]
disabled = true

[cmake]
format = "[$symbol( $version) \\(CMake\\)]($style)"
style = "blue"
symbol = " "

[cmd_duration]
min_time = 5_000
format = "[󰔟 $duration]($style)"


[character] 
success_symbol = "[❯](bold lavender)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold lavender)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

palette = "catppuccin_mocha"
