# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# $cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin
palette = "catppuccin_mocha"
right_format = """\
$docker_context\
$c$cmake\
$gradle\
$nodejs\
$rust\
$python\
$lua\
$custom\
$nim\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
"""

# Missing: LaTeX, Minecraft

format = """$username$hostname$localip\
$singularity$kubernetes\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$package\
$sudo\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[directory]
truncation_length = 5
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "blue"
read_only = " "
repo_root_style = "bold cyan"
home_symbol = "󰋜"
[directory.substitutions]
"Downloads" = "󰉍"
"Desktop" = "󰇄"
"repos" = "󰳐"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = ""
style = "subtext0"

[git_commit]
tag_symbol = "󰓹"

[git_status]
format = """\
([$staged$renamed$typechanged$count$modified](green) )\
([$untracked$deleted](red) )\
([$ahead_behind](green) )\
"""
deleted = "-$count"
staged = "+$count"
renamed = "~$count"
modified = "!$count"
untracked = "?$count"
ahead = "⇡$count"
behind = "⇣$count"

[package]
disabled = true

[c]
disabled = true

[cmake]
format = "[$symbol( $version) \\(CMake\\)]($style)"
style = "blue"
symbol = " "

[gradle]
format = "[$symbol($version)]($style) "
symbol = " "
style = "sapphire"

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "
style = "yellow"

[rust]
format = "[$symbol($version)]($style)"
style = "peach"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "󰡨"

[lua]
format = "[$symbol($version)]($style) "
symbol = "󰢱 "

[nodejs]
format = "[$symbol($version)]($style) "

[cmd_duration]
min_time = 5_000
format = "[󰔟 $duration]($style)"

[status]
format = "[$symbol $status]($style) "
disabled = false
symbol = "ERR"
not_executable_symbol = ""
not_found_symbol = "󰍉"
sigint_symbol = "INT"

[sudo]
disabled = false
format = "[su $symbol ]($style)"
symbol = "󰒓"
style = "red"

[custom.minecraft_resource]
when = ''' test -f pack.mcmeta && test -d ./assets '''
command = ''' cat pack.mcmeta | jq '.pack.pack_format' '''
symbol = "󰍳 󰉼 "
format = "[$symbol(v$output)]($style) "
style = "green bold"

[custom.minecraft_data]
when = ''' test -f pack.mcmeta && test -d ./data '''
command = ''' cat pack.mcmeta | jq '.pack.pack_format' '''
symbol = "󰍳  "
format = "[$symbol(v$output)]($style) "
style = "green bold"

[custom.latex]
detect_extensions = ["tex"]
symbol = "LaTeX "


[character]
success_symbol = "[❯](bold lavender)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold lavender)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
