#!/usr/bin/env bash

uptime="$(uptime -p | sed -e 's/up //g')"

# Icons
shutdown=󰐥
reboot=󰜉
logout=󰍃
suspend=󰏥
yes=y
no=n

run_rofi() {
  echo -e "$shutdown\n$reboot\n$suspend\n$logout" | rofi -dmenu -filter "" \
    -mesg "Power Menu (up $uptime)"
}

confirm_exit() {
  echo -e "$yes\n$no" | rofi -dmenu \
    -mesg "Are you sure? ($1)"
}

run_cmd() {
  selected="$(confirm_exit "$1")"
  if [ "$selected" == "$yes" ]; then
    if [ "$1" == "Shutdown" ]; then
      systemctl poweroff
    elif [ "$1" == "Reboot" ]; then
      systemctl reboot
    elif [ "$1" == "Logout" ]; then
      i3-msg exit
    elif [ "$1" == "Suspend" ]; then
      systemctl suspend
    fi
  else
    exit 0
  fi
}

chosen="$(run_rofi)"
case "$chosen" in
  "$shutdown")
    run_cmd Shutdown
    ;;
  "$reboot")
    run_cmd Reboot
    ;;
  "$logout")
    run_cmd Logout
    ;;
  "$suspend")
    run_cmd Suspend
    ;;
esac
