keys:
  - &global age1vum8eqs7mnm70uepcpk2du4krhn6fc5gndvn72uqshxz2tn48ggq4y8fzf
  - &ahsoka age1979mamfydsdstlyvl8uuyz97m999puu0a8hxdjw0t0sf6kd6q30sl9mquj
creation_rules:
  - path_regex: ^nixosModules/secrets/secrets\.yaml$
    key_groups:
      - age:
          - *ahsoka
          - *global
