import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
title = "Ceedrich's Terminal"
decorations_theme_variant = "Dark"
padding = { x = 5, y = 5 }

[font]
normal = { family = "JetBrainsMonoNerdFont Mono", style = "Regular" }
size = 13
